### ISSUE TITLE
[mumble] Initializing      [warning] Not connected to mumble

### ISSUE THREAD

**Issue by Snowyus** [FrazzIe/mumble-voip-fivem#103]
I took a break from FiveM RP for like a week and before mumble would connect like nothing was wrong and now all of a sudden i have tried everything and it still wont work

**Comment by iceroads** [comment]
You need to have a FiveM subscription License key enabled for OneSync in order to make it work.

As Someone pointed out, You do not need subscription for OneSync. No. But you need for mumble to be activated.
See forum: [https://forum.cfx.re/t/fivem-update-may-26th-2018/113120](https://forum.cfx.re/t/fivem-update-may-26th-2018/113120)

I quote: "This is enabled by default on the latest client/server versions if using an Element Club subscription"

**Comment by ryanwake** [comment]
> You need to have a FiveM subscription License key enabled for OneSync in order to make it work.

You do not need a subscription from Patreon for OneSync or mumble.
OneSync is free.

**Comment by Paulo-DX** [comment]
If you are using TXADMIN pls check if you have onesync infinity on, and add to the end of your ServerStarter file “+set onesync_enabled 1”.
https://gyazo.com/8317935237ca3da0c5ddfd93f0bff2e2

**Comment by AlexSimple1** [comment]
I have the same error, tried everything, read every comment nothing helped, its been 2 days  and still trying to fix it, any help? its been FiveM update and this hapenned...

**Comment by ryanwake** [comment]
> I have the same error, tried everything, read every comment nothing helped, its been 2 days and still trying to fix it, any help? its been FiveM update and this hapenned...

This is really old, but what the mentioned is the fix for this. It generally means you do not have OneSync enabled.
Please note you don't need a subscription for this on Patreon either.

**Comment by OfficialRyz** [comment]
I have tried everything and it still dont work can someone please help me
