### ISSUE TITLE
Voice not working for Face to Face but works with RP-Radio.

### ISSUE THREAD

**Issue by DanielN334** [FrazzIe/mumble-voip-fivem#109]
Hi, Im running a murmur server with mumble voip newest version and everyone connects to the mumble server correctly however face to face communication does not work however the rp-radio does. Is this a config issue or is it having issues with onesync? Thanks
[+] Also works when sitting in a car therefore looks like a chunk issue. Is there a lower version of Mumble that i should use or is it a config issue for murmur. Without the murmur server it worked fine however over 30 players mumble started failing and by 65 players only worked for a small amount of people

**Comment by Joker-CPRP** [comment]
same problem + very low sound...essential 6.4.2...help please

**Comment by DanielN334** [comment]
[UPDATE] - I fixed this by doing the far end of drastic and used an external server. It not only made it sound better however but fixed all my problems and seems to be more stable in the long run.

**Comment by TinusNL** [comment]
I also got this problem. It seams to be with some specific servers. I tested it on my test server and everything worked fine. But when i placed everything over to my main server it broke. And i could only hear people inside vehicles or via the radio.

**Comment by DaltonsDino** [comment]
Im having the same issue for rp-radio working and face to face not working, how do i resolve this?

**Comment by Local9** [comment]
Server:
OneSync: Enable
Artifacts: Latest Build

Convars;
setr voice_useSendingRangeOnly true
setr voice_use3dAudio true

Config settings for mumble-voip;
Only change is to use an external VoIP server, this is connecting correctly after updating the username wildcard and also allowing `@all` to create temporary channels.

Testing;
When a player is first connecting they can be heard and can hear others, this is understandable as the code is getting the current chunk the player is in. I've then enabled rp-radio to dig deeper and enabled debug to see what messages are being sent to the console, and also path my way through the code.

After enabling the radio, and confirming the same as many others have stated (voice works on Radio and in Vehicle, but not in proximity when face to face), I started to dig more into who the system trys to figure out who should be heard.

Looking at the events and the debug messages; when using the radio and being in a car I can see the un/muting of a player being fired; this is changing the `MumbleSetVolumeOverrideByServerId` value to -1.0 when muting them. Now, this would also then mean that after the `SetPlayerTargets` have been updated that it would mute all other players and then be 'Sending voice to Nobody', which is what happens when you leave the vehicle, or stop talking on the radio.

Looking at the `SetPlayerTargets` I can see its called inside of `SetGridTargets` but the the `gridTargets` is not passed through into `SetPlayerTargets` in turn, meaning that all players around the player are to be muted. Least this is what I can understand from how the voice targeting works.

I believe that once the `gridTargets` is corrected and passed through into `SetPlayerTargets` it should then send audio as expected as I can only assume this issue became more apparent after adding the grid system.

**Comment by Local9** [comment]
Today my testing will be done as such;

- Fresh Mumble Installation on the server
  - Only edit to the mumble server will be permissions to allow users to create temporary in Root (this error is spammed in the Mumble logs unless granted the permission)
- Have another user connect and test priximity voice
  - convars have been set as requested in every post related to the same issue
- If proximity voice fails, disable use of an external Mumble server to see if FiveMs own implementation will work and test again.

**Comment by Local9** [comment]
Sadly after going through each test and step, I've given uo trying to find a solution. I have now switched to pma-voice which gives all the perks that this project gives, and is currently actively supported by its developer.
